version: '2'

services:
  python:
    build: ./docker
    container_name: trivial
    command: bash -c "pip install -r requirements.txt && tail -f /dev/null"
    ports:
      - 8000:8000
    volumes:
      - /path/to/local/here:/opt/trivial-purfuit
